project:
  type: website
  render:
    - capacitor.qmd
    - beta_multiplier.qmd
    - parallel_lrc.qmd

website:
  title: "Analog Circuit Analysis"
  navbar:
    left:
      - href: capacitor.qmd
        text: Capacitor Analysis
      - href: beta_multiplier.qmd
        text: Beta Multiplier
      - href: parallel_lrc.qmd
        text: Parallel LRC

format:
  html:
    toc: true
    number-sections: true
